
version: '3.9'

services:
  pocketbase:
    image: alpine:latest
    container_name: pocketbase
    restart: always
    working_dir: /app
    volumes:
      - ./pb_data:/app/pb_data
      - ./pocketbase:/app
    command: ["/app/pocketbase", "serve", "--http=0.0.0.0:8090"]
    ports:
      - "8090:8090"

  nginx:
    image: nginx:latest
    container_name: nginx-menu
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - pocketbase
